version: '3.0'

name: mariadb_provider

services:
  PhpMyAdmin_MariaDB:
    image: phpmyadmin:latest
    container_name: PhpMyAdmin_MariaDB
    restart: always
    ports:
      - 798:80
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - UPLOAD_LIMIT=20M
    links:
      - MariaDB:db

  MariaDB:
    image: mariadb:latest
    container_name: MariaDB
    restart: always
    ports:
      - 3306:3306 
    environment:
      - MARIADB_USER=
      - MARIADB_PASSWORD=
      - MARIADB_ROOT_PASSWORD=

networks:
  default:
    name: mariadb_provider_network
    driver: bridge